### ISSUE TITLE
Peer-Code-Review

### ISSUE THREAD

**Issue by egichuhis** [hamzaw9/bookListManager#4]
Comments:

- Good job implementing using classes. 
- From opening your project, I can see you have not updated your README file with any information about the project. A README file is usually the first entry point for your project to enable users get started with it easily and understand the aim of the project.

**Comment by sagieramos** [comment]
Your code looks well structured. Weldone:+1: But you might want to use event delegation rather than having multiple event names of the same type. For instance, you used multiple `click` event listeners in your code, as shown in the screenshot below. 

![Screenshot from 2023-08-17 08-19-33](https://github.com/hamzaw9/bookListManager/assets/31627384/7908ea44-1ad0-48e2-be45-d54bfad1150a)

When you have redundant event type explicitly listening to different elements, this can result in an unnecessary memory overload. However, memory overload for a few event listeners might be insignificant to your app performance. But it is worth noting that event deligation can help your code run smoothly across all platforms, even on a low-end device.
